apiVersion: v1
kind: PersistentVolume
metadata:
     name: my-pv
     labels:
        app: test
spec:
   capacity:
       storage: 4Gi        
   accessModes:
       - ReadWriteOnce
   storageClassName: local-storage
   persistentVolumeReclaimPolicy: Retain  
   hostPath:
      path: /opt/mysql 

          