apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: my-pvc
     labels:
       app: test
spec:
    volumeName: my-pv
    accessModes: 
       - ReadWriteOnce
    storageClassName: local-storage
    resources:
       requests:
           storage: 4Gi   

