apiVersion:  apps/v1
kind: Deployment
metadata: 
     name: spring-mysql-app
     labels:
         app: webapp
spec:
   replicas: 1
   selector:
     matchLabels:
        app: spring-app-pod
   template:
       metadata:
            name: spring-app-pod
            labels:
               app: spring-app-pod
       spec:           
          containers:
              - name: spring-app-container
                image: ashokit/spring-boot-mysql
                ports:
                     - containerPort: 8080
                env:
                     - name: DB_DRIVER_CLASS
                       valueFrom:
                           configMapKeyRef:
                               name: my-configmap 
                               key: DB_DRIVER
                     - name: DB_HOST
                       valueFrom:
                            configMapKeyRef:
                                name: my-configmap 
                                key: DB_SERVICE_URL
                     - name: DB_NAME
                       valueFrom:
                            configMapKeyRef:
                                name: my-configmap 
                                key: DB_SCHEMA
                     - name: DB_USERNAME
                       valueFrom:
                            secretKeyRef:
                                name: my-secret
                                key: DB_USERNAME
                     - name: DB_PASSWORD
                       valueFrom:
                            secretKeyRef:
                                name: my-secret
                                key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
      name: spring-mysql-app
spec:
   selector:
         app: webapp
   type: NodePort
   ports:
       - protocol: "TCP"
         port: 8080
         targetPort: 8080
         nodePort: 31786
